### ISSUE TITLE
Discussion: chronological history

### ISSUE THREAD

**Issue by msssk** [dojo/actions#1]
One use-case for mementos that I'm not seeing explicitly accounted for is keeping the memento history in a chronological stream or queue -- each memento is time-stamped. This allows a user to select a specific point in time and get the associated memento.

I'm not seeing anything that would prevent this, just wondering if this use-case has been considered, and if the implementation is amenable to it.

**Comment by kitsonk** [comment]
I hadn't specifically considered this use case.  It was @devpaul who pointed out to me that what was in my head was aligned to the memento programming paradigm.

I could see this as something that could be composited onto the base action class.  I think this automatic state management would be too much overhead to include in the minimal class.

**Comment by msssk** [comment]
Closing this - after further discussion with @kitsonk and review of actions, they are more similar to the Command pattern than Mementos, so this is not really relevant.
