### ISSUE TITLE
Discussion: binding

### ISSUE THREAD

**Issue by msssk** [dojo/actions#2]
Should the actions package include helpers for binding to objects to automatically observe and maintain history?

**Comment by kitsonk** [comment]
That is an interesting concept.

Something like?

``` typescript
actionMutate = actionFactory({
    type: 'mutate',
    do(options: { target: Object }) {
        /* something that applies the this.state changes to target */
    },
    undo() {
       /* reverse those changes */
    },
    state: <ChangeRecords> {}
});

collector(source, actionMutate);

/* do some changes to source */

const memo = actionMutate.do({ target: dest });

memo.undo();
```

**Comment by msssk** [comment]
Closing this - after further discussion with @kitsonk and review of actions, they are more similar to the Command pattern than Mementos, so this is not really relevant.
