### ISSUE TITLE
Poor typing usability

### ISSUE THREAD

**Issue by novemberborn** [dojo/actions#21]
While working on https://github.com/dojo/examples/pull/56 I found it nearly impossible to correctly type actions.

There is an assumption that the options passed to the `do()` implementation have an `event` object, and that object has a `target` property. That makes sense when actions are used as event listeners but often actions call other actions, passing an arbitrary object.

Furthermore, the `do()` method is assumed to return a Task which resolves with the (same type as) the `target`.

Correctly changing the typing of an action requires _three_ types (`DoOptions`, `TargettedEventObject` and `ActionState`). This requires a fair amount of understanding of the action internals.

Typing an action which handles keypress events is nearly impossible since the `KeyboardEvent` type is not compatible with the `TargettedEventObject`. It has a target of course (an `HTMLElement`), but the `do()` implementation may return an entirely different object.

---

I'd like to see an interface closer to this:

``` ts
interface ActionMixin<T, O> {
  do(options?: O): Task<T>;
}

type Action<T, O> = Stateful<ActionState> & ActionMixin<T, O>;
```

The default `createAction` export should create `Action<any, any>` instances. It should take type arguments, e.g. `createAction<any, KeyboardEvent>()` should create an action that can handle keyboard events. In the TodoMVC example, a `createAction<any, Item>()` should create an action that is called with todo items.

We could export other constructors to make it easier to create the current "targeted event" actions.

---

I'm not sure whether `ActionState` deserves to be a generic. It's tempting but we can't provide default values for generics, and the more arguments `Action` takes the harder it is to customize the typing.

**Comment by kitsonk** [comment]
- [ ] `Promise` not `Task`
- [ ] Callers should NOT care about the return value, no matter what.
- [ ] `.do()` executor should always return `Promise<void>`
- [ ] Type the `.do()` arguments to be more generic and flexible
- [ ] Work better with `dojo-app` by typing `registryProvider` in factory `options` and `.configure()`
- [ ] Generic `registryProvider`

**Comment by kitsonk** [comment]
Closing as we would address this if we would ever revive this package.
